name: RESFEBER
favicon: null
layout_spectrum: 0.75276
typography_spectrum: 0.78009
title: RESFEBER
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000600'
    - '#fcfefb'
    - '#b46200'
    - '#5a595f'
    - '#f8b900'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.046361418440937996
purpose: []
